version: '3'

services:

  mongodb:
    image: "mongo:3.0.4"
    restart: always
    ports: 
      - 27017:27017
  
  
  teste-api:
    build: .
    ports:
      - 8081:8081
    depends_on:
      - mongodb
    environment:
      MONGODB_SERVER: mongodb